export const BUSINESS_INFO = {
  name: "Alenley Management",
  tagline: "Property Management",
  description: "Professional property management services in Miami-Dade and Broward County",
  phone: "(305) 699-3437",
  email: "info@alenley.com",
  website: "https://alenley.com",
  license: "Licensed Real Estate Professional",
  experience: "10+ Years Experience",
  address: {
    street: "14261 SW 120th St",
    suite: "Ste 108-694",
    city: "Miami",
    state: "FL",
    zip: "33186",
  },
  serviceAreas: [
    "Miami-Dade County",
    "Broward County",
    "Miami",
    "Fort Lauderdale",
    "Aventura",
    "Coral Gables",
    "Homestead",
    "Kendall",
  ],
  businessHours: {
    monday: "9:00 AM - 6:00 PM",
    tuesday: "9:00 AM - 6:00 PM",
    wednesday: "9:00 AM - 6:00 PM",
    thursday: "9:00 AM - 6:00 PM",
    friday: "9:00 AM - 6:00 PM",
    saturday: "By Appointment",
    sunday: "Closed",
    emergency: "24/7 for current clients",
  },
}
